import "oaidl.idl";
import "ocidl.idl";

typedef struct VoiceProperty {
  INT16 Id;
  LPWSTR Language;
  LPWSTR DisplayName;
  double SpeakingRate;
  double Volume;
  double Pitch;
} VoiceProperty;

typedef struct AudioCommand {
  INT16 AudioCommandType;
  INT16 SFXIndex;
  LPWSTR TextToSpeech;
  double WaitDuration;
} AudioCommand;

[
	object,
	dual,
	uuid(A25BD5CE-0DFD-4BD4-B85C-A77373261367)
]
interface IAudioServer : IDispatch {
	[id(1)] HRESULT Start();
	[id(2)] HRESULT Stop();
	[id(3)] HRESULT FadeIn();
	[id(4)] HRESULT FadeOut();
	[id(5)] HRESULT Push();
	[id(6)] HRESULT GetVoiceCount();
	[id(7)] HRESULT GetDefaultVoice();
	[id(8)] HRESULT GetVoiceProperty();
	[id(9)] HRESULT SetDefaultVoice();
	[id(10)] HRESULT SetVoiceProperty();
}
[
	uuid(30C033DF-A924-406B-81CE-FAEF6DFEA5BD),
	version(1.0),
	helpstring("Type library for audio server")
]
library AudioServerLib {
	importlib("stdole2.tlb");
	[
		uuid(F9353078-F40A-4ED5-8354-039E805D2DF8)
	]
	coclass AudioServer
	{
		[default] interface IAudioServer;
	}
}
