import "oaidl.idl";
import "ocidl.idl";

typedef [v1_enum] enum {
	LOGLEVEL_NONE = 0,
	LOGLEVEL_INFO = 1,
	LOGLEVEL_WARN = 2,
	LOGLEVEL_FAIL = 3
} LOGLEVEL;

typedef INT64(__stdcall *NotifyIdleStateHandler)(INT64 id);

typedef struct RawVoiceProperty {
  LPWSTR Language;
  LPWSTR DisplayName;
  double SpeakingRate;
  double Volume;
  double Pitch;
} RawVoiceProperty;

typedef struct RawCommand {
  INT16 Type;
  INT16 SFXIndex;
  LPWSTR TextToSpeech;
  double WaitDuration;
} RawCommand;

[
	object,
	dual,
	uuid(A25BD5CE-0DFD-4BD4-B85C-A77373261367)
]
interface IAudioServer : IDispatch {
	[id(1), local] HRESULT Start([in] LPWSTR soundEffectsPath, [in] LPWSTR loggerURL, [in] LOGLEVEL level);
	[id(2), local] HRESULT Stop();
	[id(3), local] HRESULT FadeIn();
	[id(4), local] HRESULT FadeOut();
	[id(5), local] HRESULT Push([in] RawCommand **pCommands, [in] INT32 commandsLength, [in] INT32 isForcePush);
	[id(6), local] HRESULT GetVoiceCount([out] INT32 *pVoiceCount);
	[id(7), local] HRESULT GetDefaultVoice([out] INT32 *pVoiceIndex);
	[id(8), local] HRESULT GetVoiceProperty([in] INT32 voiceIndex, [out] RawVoiceProperty **ppVoiceProperty);
	[id(9), local] HRESULT SetDefaultVoice([in] INT32 voiceIndex);
	[id(10), local] HRESULT SetVoiceProperty([in] INT32 voiceIndex, [in] RawVoiceProperty *pVoiceProperty);
	[id(11), local] HRESULT SetNotifyIdleStateHandler([in] NotifyIdleStateHandler notifyIdleStateHandler);
	[id(12), local] HRESULT TestArray([in] INT32 *pArray);
}
[
	uuid(30C033DF-A924-406B-81CE-FAEF6DFEA5BD),
	version(1.0),
	helpstring("Type library for audio server")
]
library AudioServerLib {
	importlib("stdole2.tlb");
	[
		uuid(F9353078-F40A-4ED5-8354-039E805D2DF8)
	]
	coclass AudioServer
	{
		[default] interface IAudioServer;
	}
}
